USE [SUMC]
GO

/****** Object:  Table [dbo].[Way]    Script Date: 07/07/2022 15:58:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Way](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[line_id] [int] NOT NULL,
	[way] [bit] NOT NULL,
 CONSTRAINT [PK_Way] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

